### ISSUE TITLE
Ability to generate custom build with reduced set of features

### ISSUE THREAD

**Issue by Oza94** [GoodBoyDigital/pixi.js#1283]
Hello,

I just moved on Pixi.js for my HTML5 game and I love this library!

I wonder if it is possible (or planned) to generate a custom build of pixi to include only the used features (and their dependencies)? My main motivations are :

 * I do not use loaders (and other few things) since it is handled by the engine itself
 * An HTML5 game can be quite heavy to load, each removed byte is a good thing

In my opinion, since the Pixi is already wrapped in separate "classes" and files, a "partial build" feature should be easy to implement with grunt.

**Comment by mattdesl** [comment]
> User expectations while waiting for a game to load are vastly different to those encountered while waiting for a web page to load.

Making mobile users wait *several seconds* on a white screen (with no response because of blocking script parse/execution) is a pretty terrible UX regardless of whether we are discussing websites or games. 

Keep in mind -- with SPAs and browser bundles, a game is often tied to the website that surrounds and delivers it. And, of course, many of us are not using Pixi to just build games. ;) e.g. see the Pixi-powered McDonalds microsites.

**Comment by englercj** [comment]
You can do this now in v3 by running `gulp` with a command line switch of what feature to exclude. Features you can exclude currently are:

- extras
- filters
- interaction
- loaders
- spine
- text

For example, if I didn't want spine or extras:

```sh
gulp -e extras -e spine
```

and my output bundle would not include those items.

**Comment by serprex** [comment]
I tried "gulp -e loaders -e spine -e extras"

While pixi.min.js has reduced those modules, pixi.js still includes them

**Comment by englercj** [comment]
It shouldn't be including them in the main bundle, I didn't see them their when I looked earlier. The reason the dev bundle is so large is not because of our code but because the sourcemap is embedded. The take that out and we will probably be less than 500K.

**Comment by serprex** [comment]
Messed around with things, seems I indeed am unable to use get ignore working. Arguments are being passed to the ignore loop, but browserify doesn't seem to care (also tried setting basedir & ignoring src/module, to no avail)

**Comment by englercj** [comment]
We use browserify v8, sooo you should probably upgrade..

**Comment by thomfoolery** [comment]
I'm trying to build a diet version of PixiJS using the 'dev' branch but no matter what I try to exclude using -e argument the resulting files in the bin folder are always the same size. Is there something I am missing?

**Comment by englercj** [comment]
Hmm, ignore doesn't seem to be working. not sure whats up. I'll try to look at this soon.

**Comment by englercj** [comment]
Got this fixed by the way in the latest `dev` code.

**Comment by Friksel** [comment]
The issue of modules not being excluded during build in v3 as described by @thomfoolery I'm having at v4.2.2 right now. Perhaps the same issue is back again in v4?  : #3322

**Comment by PierBover** [comment]
For anyone wondering how to do this for v4 you have to edit the `dist` command in `package.json` with something like this:

`pixify -d dist -n PIXI -o pixi -e accessibility -e extras -e filters -e mesh -e particles -t babelify`
