### ISSUE TITLE
PIXI.Text cutting off top of text on some fonts

### ISSUE THREAD

**Issue by baseten** [GoodBoyDigital/pixi.js#1527]
See fiddle here: http://jsfiddle.net/uexztot4/1/

The top of the text is cropped off, I'm guessing the calculation for the ascender is off here, or is there an issue with the font itself?

**Comment by englercj** [comment]
In v3 there is a padding property that allows you to fix issues like this.

**Comment by baseten** [comment]
Thanks, is v3 relatively stable at the moment? I need to use this particular font on a current project. Are there any changes in the API in v3?

**Comment by englercj** [comment]
@baseten A few, but they should be easy to catch and remedy. Many of them are backed by a backwards compatibility layer that warns you in console.

**Comment by GoodBoyDigital** [comment]
Hey all! Gonna close this as the issue is fixed in v3. Cheers peeps :+1:

**Comment by pietervanneste** [comment]
Hi @GoodBoyDigital,

I think the problem still exists. I updated the jsfiddle with pixi v4 and the new text-syntax.
See here: http://jsfiddle.net/0fneuguv/

Is there already a better fix than playing with the padding?

Thx Pieter

**Comment by themoonrat** [comment]
The static measureFont function within TextMetrics.js is what tries to get a handle on how tall text will be when rendered to a canvas. It is a slight guesswork, however, as you can measure text width wise on a canvas, but not height wise. So we create a canvas we think will almost certainly be taller, then measure pixels drawn to that canvas to get the true height. In that process are a couple of magic numbers like
```
const height = 2 * baseline;
baseline = baseline * 1.4 | 0;
```
It's basically looking at the width of an M, and saying, ok, lets say that the tallest text can be is double the width of the widest letter, M. The font you are using is unusually tall, so this turns out not to work. When i double both of those values to 4 * baseline and baseline * 2.8, the text looks fine.

**Comment by pietervanneste** [comment]
@themoonrat thanks for your response, but for my project it's not an option to do that. 

Any other ideas ?

**Comment by baseten** [comment]
Perhaps these values could be measured in invisible HTML elements during some kind of initialisation step and cached for each font?
