### ISSUE TITLE
[v3] Retina assets not scaling correctly on canvas

### ISSUE THREAD

**Issue by adireddy** [GoodBoyDigital/pixi.js#1559]
On canvas desktop/device retina assets are not scaling correctly.

Tested on Safari by disabling webgl on desktop.
Test URL: http://adireddy.github.io/demos/haxe-pixi/v3/retina.html

**Comment by englercj** [comment]
To confirm, this is on v3 correct?

**Comment by adireddy** [comment]
yes

**Comment by GoodBoyDigital** [comment]
hey there @adireddy! do you have a js fiddle we could play around with that highlights the issue please?

cheers!

**Comment by adireddy** [comment]
Here you go @GoodBoyDigital http://jsfiddle.net/adireddy/7La103L1/3/

Note that the code was exported from Haxe.

Works fine on WebGL and just tried again on Safari disabling WebGL and it doesn't work.

**Comment by GoodBoyDigital** [comment]
Perfect! thanks, thats fixed now in the dev branch :+1:

**Comment by adireddy** [comment]
Just tested and the issue still present @GoodBoyDigital  http://jsfiddle.net/7La103L1/6/

**Comment by GoodBoyDigital** [comment]
you may need to rebuild pixi to see the fix as I only upload the src code fix

**Comment by adireddy** [comment]
Built from dev but still the same issue.

Also noticed another issue in the dev branch.
`TypeError: undefined is not an object (evaluating 'new core.math.Rectangle') in siriteSheetParser.js:41`

**Comment by GoodBoyDigital** [comment]
heres the demo i was using -> http://jsfiddle.net/pg9b4ncu/
seems ok?

**Comment by adireddy** [comment]
It's fine if the `resolution` is not set.

I am setting the renderer resolution property. http://jsfiddle.net/adireddy/pg9b4ncu/1/

**Comment by GoodBoyDigital** [comment]
gotcha! watch this space...

**Comment by GoodBoyDigital** [comment]
http://jsfiddle.net/cLgo0b7w/

hows this one?

**Comment by adireddy** [comment]
Perfect :+1: 

Thanks @GoodBoyDigital

**Comment by adireddy** [comment]
Found another minor issue... positioning is not correct when compared between webgl and canvas.
`_img.anchor.set(0.5, 0.5);`
`_img.position.set(Browser.window.innerWidth / 2, Browser.window.innerHeight / 2);`

http://jsfiddle.net/adireddy/cLgo0b7w/1/
