### ISSUE TITLE
TilingSprite Errors

### ISSUE THREAD

**Issue by georgiee** [GoodBoyDigital/pixi.js#1683]
I just gave RC4 a try. I was a very easy transition from v2. Well done and thanks for this! But TilingSprite seems to be a difficult child for now.

## 1. Still messy borders
See here: http://jsfiddle.net/cc6r8s7n/4/
This is my old and closed issue to this: https://github.com/GoodBoyDigital/pixi.js/issues/1457
There are messy borders or the might ne gaps of a single pixel.
(The stretching error (see https://github.com/GoodBoyDigital/pixi.js/issues/1458) is fixed as far as I can test for now)

Might be related to this ?
https://github.com/GoodBoyDigital/pixi.js/issues/1630

## 2. No Canvas rendering
See here: http://jsfiddle.net/cc6r8s7n/4/
Same here: https://github.com/GoodBoyDigital/pixi.js/issues/1659
I also tracked it down to `generateTilingTexture`. Even by using the correct method signature it will fail at 
`renderer.currentRenderer.flush();`
<a href='https://github.com/GoodBoyDigital/pixi.js/blob/03c9133b2b1a5319b4ea748a06e7bdbf1c299c5c/src/extras/TilingSprite.js#L391' target='_blank'>TilingSprite.js#L391</a>

This is where I stopped to investigate into it.

**Comment by GoodBoyDigital** [comment]
hey there, just uploaded a new Tiling texture to the dev branch.. please let me know if it works ok for ya!

**Comment by krzysztof-o** [comment]
Canvas seems to be fixed, but WebGL version stopped working for me (no errors in the console).

**Comment by GoodBoyDigital** [comment]
hmm.. the fiddle works like a boss for me?

**Comment by krzysztof-o** [comment]
I'll double-check it, but it was working fine before the last update.

**Comment by GoodBoyDigital** [comment]
webGL got a bit or a teardown - its now tiling in the shader rather than generating a PoT texture as it was before...

**Comment by krzysztof-o** [comment]
Maybe it's nor working for me because I'm using a tile from a spritesheet.

**Comment by georgiee** [comment]
Yes! This looks promising so far. Gaps are gone, canvas is running. My tiles are loaded from different spritesheets. But there is a display problem in the canvas renderer with Background Tiling Sprites which are only moved with tilePosition.x. They just disappears if the x position is large enough. It's running totally fine so I guess it's a bug with the canvas renderer ? I will provide you with a fiddle for this.

**Comment by GoodBoyDigital** [comment]
Great to hear @georgiee :+1: 

@krzysztof-o 
was testing this one: http://jsfiddle.net/t5cvsbww/
it uses a sprite sheet and seems to be all cool?

**Comment by georgiee** [comment]
Okay. That was easy to reproduce. I hope it's the same to fix it :)

Bug Description:
Only in Canvas: If the horizontal tilePosition is larger than the tile width itself the tile disappears. This might be the same for the vertical equivalent.


Here is the fiddle with two dat gui controls to change the position and the width of the tile.
http://jsfiddle.net/ym4zcj8k/

Here two screenshots. The TilingSprite should span the whole window as it's shown in the first screenshot.

![screen shot 2015-04-20 at 18 14 54](https://cloud.githubusercontent.com/assets/1701755/7234725/546bcee2-e789-11e4-8d37-5febe0715db3.png)
![screen shot 2015-04-20 at 18 14 49](https://cloud.githubusercontent.com/assets/1701755/7234724/54696210-e789-11e4-8cf2-b0f017039dc0.png)

Thank you very much for this new TilingSprite component!

**Comment by krzysztof-o** [comment]
I found the problem. When the tile image is 1px width it doesn't appear. As soon as I resized it to 2px it started working.

**Comment by georgiee** [comment]
@GoodBoyDigital 

> webGL got a bit or a teardown - its now tiling in the shader rather than generating a PoT texture as it was before...

At the moment I am in the process of performance testing my current application on a iPad2 device. I just rechecked it and gained 30fps, so that I'm now at 60fps. What a great decision to move the tiling to the shader. You just saved me from a very tedious profiling session. Wonderful! :sparkles: :thumbsup:

**Comment by GoodBoyDigital** [comment]
@georgiee happy days, great to hear! :D

**Comment by GoodBoyDigital** [comment]
should be fixed now on the dev branch @georgiee :+1:

**Comment by georgiee** [comment]
YES. Confirmed. Fixed! Thank you very much! It's my pleasure to close this ticket.

**Comment by krzysztof-o** [comment]
@GoodBoyDigital, the issue with 1px-width tile still exists in WebGL renderer.

**Comment by GoodBoyDigital** [comment]
@krzysztof-o - is that from a sprite sheet?

**Comment by krzysztof-o** [comment]
Yes, the tile is 1px width (the spritesheet itself is larger).

**Comment by GoodBoyDigital** [comment]
cool - due to precision issue this is going to be pretty tricky to fix. Any reason why you are using a 1 px tiling sprite? Graphics Object would be much nicer?

**Comment by krzysztof-o** [comment]
But I can't achieve gradients in Graphics Object.
Resizing to 2px works for me but it seems like a dirty workaround.
This is the tile I'm using:
![background_tile](https://cloud.githubusercontent.com/assets/381234/7238957/8162d81a-e7a6-11e4-90c7-c095be2c0751.png)

**Comment by GoodBoyDigital** [comment]
i see! for now this is the best way to go is to do 2px width. I will have a think about a workaround.. cheers!

**Comment by krzysztof-o** [comment]
Ok, thanks a lot!

**Comment by georgiee** [comment]
Hey, I got another small bug for you in webgl and canvas. The tiling sprite will jump if the tilingPosition is past the width of the base texture.  See http://jsfiddle.net/ym4zcj8k/3/ and test the tiling position around 512 or 1024

The tiling sprite will jump when you pass a multiple of the width of the base texture which is 512 in this example. I think this is the error in the code for webgl.
https://github.com/GoodBoyDigital/pixi.js/blob/b68ab0f5ca4cc617d2725107501c41107f9e6f3f/src/extras/TilingSprite.js#L200

```
It should be modulo the real width of the given tiling texture. But contains the width of the whole spritesheet.
this.shader.uniforms.uTransform.value[0] = (this.tilePosition.x % tw) / this._width;
this.shader.uniforms.uTransform.value[1] = (this.tilePosition.y % th) / this._height;
```

**Comment by JiDW** [comment]
Hey @georgiee , did you find a fix for this one please ?

**Comment by georgiee** [comment]
Na, I did not look into it yet as the deadline for my current project is far enough in the future so I'm just betting on a fix with some upcoming commits. I still think my suggested fix could work but I hadn't time to try it yet. You could easily monkey patch and test it yourself. Just copy the TilingSprite source from this repository, override the necessary code parts and give it a try by including it after the pixi library.

**Comment by JiDW** [comment]
I tried but it didn't work.

for me, this piece of code isn't working for every cases : 

```javascript
// apply padding to stop gaps in the tile when numbers are not rounded
    this.shader.uniforms.uFrame.value[0] = tempUvs.x0 + (0.5 / tw); // the 0.5 is padding
    this.shader.uniforms.uFrame.value[1] = tempUvs.y0 + (0.5 / th); // the 0.5 is padding
    this.shader.uniforms.uFrame.value[2] = tempUvs.x1 - tempUvs.x0 + (-1 / tw); // the -1 is padding offset
    this.shader.uniforms.uFrame.value[3] = tempUvs.y2 - tempUvs.y0 + (-1 / th); // the -1 is padding offset
```

I Have a texture inside a spritesheet. I only repeat on Y. This means my tilingtexture.width is equal to the frame width.

First, I add to remove the 0.5 padding on x to not get an extra pixel on the right.
Then, I tried to toy with the y padding offset but depending on my tilingsprite position, I didn't find a value able to fix every tests.

This is very visible in my game because my tilingsprites are inside a scrollable container. So I can see the gaps blinking when I scroll.

https://cloud.githubusercontent.com/assets/581736/7416695/7c3aa18e-ef61-11e4-8c06-b6f2927dc917.png

https://cloud.githubusercontent.com/assets/581736/7416718/a50be24e-ef61-11e4-8242-75b757345d5b.png

**Comment by weepy** [comment]
Here's a very simple fiddle showing TilingSprite generating a texture that repeats 1px too early.

https://jsfiddle.net/ya9b73qk/1/

**Comment by englercj** [comment]
I was able to get @weepy's test case working correctly by removing the padding completely.

I'm curious if you (@JiDW) have tried using `0` instead of the `0.5` and `-1` padding (or just remove the padding thing completely) and did that work for your cases? It works for the cases I have lying around.

**Comment by englercj** [comment]
I think I managed to kill all these issues here with the latest dev code. Let me know if you build the latest dev and it still doesn't work for you!

I was able to get all the test cases posted here working (along with our own examples and such).

**Comment by georgiee** [comment]
I can confirm that the jumping doesn't happen anymore. Thanks Chad!

**Comment by weepy** [comment]
heya englercj

i've tried the latest 3.0.5 and also from source, but i still seem to get the same problem as reported in https://jsfiddle.net/ya9b73qk/1/

do you have a fiddle showing it working?

**Comment by englercj** [comment]
I updated the URL of the pixi library you were loading to 3.0.5 and it works fine:

https://jsfiddle.net/ya9b73qk/2/

**Comment by weepy** [comment]
apologies my bad. i confirm it works well

**Comment by duanhaoyi** [comment]
pixi.js - v3.0.10

I have a "Repeat 2nd row&col as 1st row&col" webgl renderer issue on TilingSprite on my chrome 53.0.2785.143 m(64-bit) win7 AMD Readeon 6800, (also happens to NW.js build on the same machine), chrome version may varying cauz I found the same thing on early chrome version:

I'm working on a pixel style game so I set
**_PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST;_**

and I just make a TilingSprite like :
**_var bg = new PIXI.extras.TilingSprite(texture, 100, 100);_**

This is my test texture (16x16 or any resolution or using sprite sheet).
![9s](https://cloud.githubusercontent.com/assets/1532931/19456598/85d9463e-94c2-11e6-87bf-b04eef9b17fc.png) ![qq 20161017233724](https://cloud.githubusercontent.com/assets/1532931/19456627/ab3d8854-94c2-11e6-83f6-6e2ec600ef77.png) 

This is the result:
![qq 20161017233928](https://cloud.githubusercontent.com/assets/1532931/19456706/f349c22a-94c2-11e6-9a8d-5a1fec20e351.png) ![qq 20161017233928](https://cloud.githubusercontent.com/assets/1532931/19456751/3514f9e0-94c3-11e6-82e1-35bb5f65cfcd.png)

But the result SHOULD BE:
![qq 20161017234559](https://cloud.githubusercontent.com/assets/1532931/19456902/029e9fa6-94c4-11e6-9730-6f72e4272a8d.png)![qq 20161017234559](https://cloud.githubusercontent.com/assets/1532931/19456926/156ecbec-94c4-11e6-8b91-cfbe97c38dc7.png)

As you can see,there's an 1 pixel offset issue: every tile's 1st row&col **_is replaced_** by the 2nd row&col. 
As i'm running out of the time, I do not have much time thinking, so I just pray to my mysterious ancient power in vain and they point me at the fragment shader of TilingSprite:
**_coord = clamp(coord, uPixelSize, uFrame.zw-uPixelSize);_**
then I enlarge the clamp a little bit, hope that will cheat the floating processor to give my 1st pixel row&col back:
**_coord = clamp(coord, uPixelSize-0.001, uFrame.zw-uPixelSize+0.001);_**

Then it just works. (0.001 or 0.0001 or 0.00001 or whatever)

I do not kno it's just me or my machine or  it's actually an issue, but may be some one could use it as a very DIRTY solution while you're on the same boat.

times out =.=!!

**Comment by ivanpopelyshev** [comment]
@duanhaoyi 
Please use latest pixi instead of 3.0.10, I just fixed those issues two weeks ago
